type: m
empty: false
manager:
  address: 127.0.0.1:6001
  password: 'YOURPASSWD'
plugins:
  watch:
    use: true
    host: '127.0.0.1'
    port: '90'
    site: 'http://127.0.0.1:90/'
  webgui:
    use: true
    host: '127.0.0.1'
    port: '80'
    site: 'http://127.0.0.1/'
    gcmSenderId: '456102641793'
    gcmAPIKey: 'AAAAGzzdqrE:XXXXXXXXXXXXXX'
db:
  host: '127.0.0.1'
  user: 'root'
  password: 'appwatch2017'
  database: 'appwatch'